### ISSUE TITLE
Backend not working

### ISSUE THREAD

**Issue by Simon-Davies** [ThisIsLibra/genesis#9]
I have got the Frontend set up fine but I am having issues with the backend.

I have deployed the genesis-1.0.war file using the GlassFish Server but I am getting the below error in the Web Developer - Network tab:

Request URL:http://localhost:8080/genesis/api/v1/snippets/languages
Request method:GET
Remote address:127.0.0.1:8080
Status code:
404
Version:HTTP/1.1
Referrer Policy:no-referrer-when-downgrade

Can you please give instructions on how to deploy the genesis-1.0.war file so it works please. Thanks in advance.

**Comment by ThisIsLibra** [comment]
Hello Simon,

In this case, I launched the Glassfish server and went to the administration panel on localhost:4848. By opening the applications menu on the left, you can deploy the WAR using a local file. Select the "Enterprise Application" as type, select the virtual server you wish to use ("server" is the one that you would use if you have no other ones). Check the "status", "implicit CDI", and force redeploy checkboxes.

You will then see the deployed WAR in the list of applications When you press launch there, select a link in the pop-up menu. Use the that link as the base address in the variable that needs to be exported for the front-end. To see if it works, append "api/v1/status/version" to the URL and visit it. This should return a JSON value that contains the version of Genesis.

This has been tested on GlassFish 4.1.1 (build 1).

**Comment by Simon-Davies** [comment]
Thank you for your reply. I will try this today :)
